/* See LICENCE for license details */

/*

Module: feed_const.h

Description:

    Constants shared for all modules.

*/

#define FEED_ESC_CHAR '\033'

#define FEED_CSI_CUU 'A'
#define FEED_CSI_CUD 'B'
#define FEED_CSI_CUF 'C'
#define FEED_CSI_CUB 'D'
#define FEED_CSI_ED 'J'
#define FEED_CSI_EL 'K'
#define FEED_CSI_CUP 'H'
#define FEED_CSI_SGR 'm'

#define FEED_SGR_RESET 0
#define FEED_SGR_BOLD 1
#define FEED_SGR_FAINT 2
#define FEED_SGR_ITALIC 3
#define FEED_SGR_UNDERLINE 4
#define FEED_SGR_SLOW_BLINK 5
#define FEED_SGR_RAPID_BLINK 6
#define FEED_SGR_REVERSE_VIDEO 7
#define FEED_SGR_CONCEAL 8
#define FEED_SGR_CROSSED_OUT 9
#define FEED_SGR_PRIMARY_FONT 10
#define FEED_SGR_ALTERNATE_FONT 11
#define FEED_SGR_FRAKTUR 20
#define FEED_SGR_BOLD_OFF 21
#define FEED_SGR_NORMAL 22
#define FEED_SGR_ITALIC_OFF 23
#define FEED_SGR_UNDERLINE_OFF 24
#define FEED_SGR_BLINK_OFF 25
#define FEED_SGR_INVERSE_OFF 27
#define FEED_SGR_REVEAL 28
#define FEED_SGR_NOT_CROSSED_OUT 29
#define FEED_SGR_FOREGROUND 30
#define FEED_SGR_SET_FOREGROUND_RGB 38
#define FEED_SGR_DEFAULT_FOREGROUND 39
#define FEED_SGR_BACKGROUND 40
#define FEED_SGR_SET_BACKGROUND_COLOR 48
#define FEED_SGR_DEFAULT_BACKGROUND 49
#define FEED_SGR_FRAMED 51
#define FEED_SGR_ENCIRCLED 52
#define FEED_SGR_OVERLINED 53
#define FEED_SGR_BRIGHT_FOREGROUND 90
#define FEED_SGR_BRIGHT_BACKGROUND 100

